vim.g.mapleader = ' '

vim.keymap.set('', '<leader>q', ':q!<CR>')
vim.keymap.set('', '<leader>w', ':w<CR>')
vim.keymap.set('', '<leader>f', ':wq<CR>')
--vim.keymap.set('', '<leader>w', function()
--    vim.lsp.buf.format()
--    vim.cmd('w')
--end, { desc = 'format & w' })
--vim.keymap.set('', '<leader>f', function()
--    vim.lsp.buf.format()
--    vim.cmd('wq')
--end, { desc = 'format & wq' })
vim.keymap.set('', '<leader>j', ':nohl<CR>')
vim.keymap.set('', 'n', 'h')
vim.keymap.set('', 'o', 'l')
vim.keymap.set('', 'e', 'j')
vim.keymap.set('', 'i', 'k')
vim.keymap.set('', 'h', 'i')
vim.keymap.set('', 'k', 'e')
vim.keymap.set('', 'j', 'nzz')
vim.keymap.set('', 'l', 'o')
vim.keymap.set('', 'N', '10h')
vim.keymap.set('', 'O', '10l')
vim.keymap.set('', 'E', '10j')
vim.keymap.set('', 'I', '10k')
vim.keymap.set('', 'H', 'I')
vim.keymap.set('', 'K', 'E')
vim.keymap.set('', 'J', 'Nzz')
vim.keymap.set('', 'L', 'O')

vim.cmd('nohl')
